version: '3.8'
services:
  infinispan:
    image: infinispan/server:latest
    restart: always
    ports:
      - "11222:11222"
    environment:
      USER: admin
      PASS: password
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authors
      POSTGRES_USER: authors
      POSTGRES_PASSWORD: authors